/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopsRouteImport } from './routes/workshops'
import { Route as TeachingRouteImport } from './routes/teaching'
import { Route as SocialServicesRouteImport } from './routes/social-services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as PatientEducationRouteImport } from './routes/patient-education'
import { Route as LinksRouteImport } from './routes/links'
import { Route as InnovativeTeachingRouteImport } from './routes/innovative-teaching'
import { Route as Icem2026RouteImport } from './routes/icem-2026'
import { Route as FirstAidRouteImport } from './routes/first-aid'
import { Route as EmDiariesRouteImport } from './routes/em-diaries'
import { Route as ElectivesRouteImport } from './routes/electives'
import { Route as DisasterManagementRouteImport } from './routes/disaster-management'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AiAppsRouteImport } from './routes/ai-apps'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InnovativeTeachingMethodIdRouteImport } from './routes/innovative-teaching.$methodId'

const WorkshopsRoute = WorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachingRoute = TeachingRouteImport.update({
  id: '/teaching',
  path: '/teaching',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialServicesRoute = SocialServicesRouteImport.update({
  id: '/social-services',
  path: '/social-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientEducationRoute = PatientEducationRouteImport.update({
  id: '/patient-education',
  path: '/patient-education',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovativeTeachingRoute = InnovativeTeachingRouteImport.update({
  id: '/innovative-teaching',
  path: '/innovative-teaching',
  getParentRoute: () => rootRouteImport,
} as any)
const Icem2026Route = Icem2026RouteImport.update({
  id: '/icem-2026',
  path: '/icem-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstAidRoute = FirstAidRouteImport.update({
  id: '/first-aid',
  path: '/first-aid',
  getParentRoute: () => rootRouteImport,
} as any)
const EmDiariesRoute = EmDiariesRouteImport.update({
  id: '/em-diaries',
  path: '/em-diaries',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectivesRoute = ElectivesRouteImport.update({
  id: '/electives',
  path: '/electives',
  getParentRoute: () => rootRouteImport,
} as any)
const DisasterManagementRoute = DisasterManagementRouteImport.update({
  id: '/disaster-management',
  path: '/disaster-management',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAppsRoute = AiAppsRouteImport.update({
  id: '/ai-apps',
  path: '/ai-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovativeTeachingMethodIdRoute =
  InnovativeTeachingMethodIdRouteImport.update({
    id: '/$methodId',
    path: '/$methodId',
    getParentRoute: () => InnovativeTeachingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-apps': typeof AiAppsRoute
  '/contact': typeof ContactRoute
  '/disaster-management': typeof DisasterManagementRoute
  '/electives': typeof ElectivesRoute
  '/em-diaries': typeof EmDiariesRoute
  '/first-aid': typeof FirstAidRoute
  '/icem-2026': typeof Icem2026Route
  '/innovative-teaching': typeof InnovativeTeachingRouteWithChildren
  '/links': typeof LinksRoute
  '/patient-education': typeof PatientEducationRoute
  '/research': typeof ResearchRoute
  '/resources': typeof ResourcesRoute
  '/social-services': typeof SocialServicesRoute
  '/teaching': typeof TeachingRoute
  '/workshops': typeof WorkshopsRoute
  '/innovative-teaching/$methodId': typeof InnovativeTeachingMethodIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-apps': typeof AiAppsRoute
  '/contact': typeof ContactRoute
  '/disaster-management': typeof DisasterManagementRoute
  '/electives': typeof ElectivesRoute
  '/em-diaries': typeof EmDiariesRoute
  '/first-aid': typeof FirstAidRoute
  '/icem-2026': typeof Icem2026Route
  '/innovative-teaching': typeof InnovativeTeachingRouteWithChildren
  '/links': typeof LinksRoute
  '/patient-education': typeof PatientEducationRoute
  '/research': typeof ResearchRoute
  '/resources': typeof ResourcesRoute
  '/social-services': typeof SocialServicesRoute
  '/teaching': typeof TeachingRoute
  '/workshops': typeof WorkshopsRoute
  '/innovative-teaching/$methodId': typeof InnovativeTeachingMethodIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-apps': typeof AiAppsRoute
  '/contact': typeof ContactRoute
  '/disaster-management': typeof DisasterManagementRoute
  '/electives': typeof ElectivesRoute
  '/em-diaries': typeof EmDiariesRoute
  '/first-aid': typeof FirstAidRoute
  '/icem-2026': typeof Icem2026Route
  '/innovative-teaching': typeof InnovativeTeachingRouteWithChildren
  '/links': typeof LinksRoute
  '/patient-education': typeof PatientEducationRoute
  '/research': typeof ResearchRoute
  '/resources': typeof ResourcesRoute
  '/social-services': typeof SocialServicesRoute
  '/teaching': typeof TeachingRoute
  '/workshops': typeof WorkshopsRoute
  '/innovative-teaching/$methodId': typeof InnovativeTeachingMethodIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-apps'
    | '/contact'
    | '/disaster-management'
    | '/electives'
    | '/em-diaries'
    | '/first-aid'
    | '/icem-2026'
    | '/innovative-teaching'
    | '/links'
    | '/patient-education'
    | '/research'
    | '/resources'
    | '/social-services'
    | '/teaching'
    | '/workshops'
    | '/innovative-teaching/$methodId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-apps'
    | '/contact'
    | '/disaster-management'
    | '/electives'
    | '/em-diaries'
    | '/first-aid'
    | '/icem-2026'
    | '/innovative-teaching'
    | '/links'
    | '/patient-education'
    | '/research'
    | '/resources'
    | '/social-services'
    | '/teaching'
    | '/workshops'
    | '/innovative-teaching/$methodId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-apps'
    | '/contact'
    | '/disaster-management'
    | '/electives'
    | '/em-diaries'
    | '/first-aid'
    | '/icem-2026'
    | '/innovative-teaching'
    | '/links'
    | '/patient-education'
    | '/research'
    | '/resources'
    | '/social-services'
    | '/teaching'
    | '/workshops'
    | '/innovative-teaching/$methodId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiAppsRoute: typeof AiAppsRoute
  ContactRoute: typeof ContactRoute
  DisasterManagementRoute: typeof DisasterManagementRoute
  ElectivesRoute: typeof ElectivesRoute
  EmDiariesRoute: typeof EmDiariesRoute
  FirstAidRoute: typeof FirstAidRoute
  Icem2026Route: typeof Icem2026Route
  InnovativeTeachingRoute: typeof InnovativeTeachingRouteWithChildren
  LinksRoute: typeof LinksRoute
  PatientEducationRoute: typeof PatientEducationRoute
  ResearchRoute: typeof ResearchRoute
  ResourcesRoute: typeof ResourcesRoute
  SocialServicesRoute: typeof SocialServicesRoute
  TeachingRoute: typeof TeachingRoute
  WorkshopsRoute: typeof WorkshopsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshops': {
      id: '/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teaching': {
      id: '/teaching'
      path: '/teaching'
      fullPath: '/teaching'
      preLoaderRoute: typeof TeachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-services': {
      id: '/social-services'
      path: '/social-services'
      fullPath: '/social-services'
      preLoaderRoute: typeof SocialServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-education': {
      id: '/patient-education'
      path: '/patient-education'
      fullPath: '/patient-education'
      preLoaderRoute: typeof PatientEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovative-teaching': {
      id: '/innovative-teaching'
      path: '/innovative-teaching'
      fullPath: '/innovative-teaching'
      preLoaderRoute: typeof InnovativeTeachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icem-2026': {
      id: '/icem-2026'
      path: '/icem-2026'
      fullPath: '/icem-2026'
      preLoaderRoute: typeof Icem2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-aid': {
      id: '/first-aid'
      path: '/first-aid'
      fullPath: '/first-aid'
      preLoaderRoute: typeof FirstAidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/em-diaries': {
      id: '/em-diaries'
      path: '/em-diaries'
      fullPath: '/em-diaries'
      preLoaderRoute: typeof EmDiariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electives': {
      id: '/electives'
      path: '/electives'
      fullPath: '/electives'
      preLoaderRoute: typeof ElectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disaster-management': {
      id: '/disaster-management'
      path: '/disaster-management'
      fullPath: '/disaster-management'
      preLoaderRoute: typeof DisasterManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-apps': {
      id: '/ai-apps'
      path: '/ai-apps'
      fullPath: '/ai-apps'
      preLoaderRoute: typeof AiAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovative-teaching/$methodId': {
      id: '/innovative-teaching/$methodId'
      path: '/$methodId'
      fullPath: '/innovative-teaching/$methodId'
      preLoaderRoute: typeof InnovativeTeachingMethodIdRouteImport
      parentRoute: typeof InnovativeTeachingRoute
    }
  }
}

interface InnovativeTeachingRouteChildren {
  InnovativeTeachingMethodIdRoute: typeof InnovativeTeachingMethodIdRoute
}

const InnovativeTeachingRouteChildren: InnovativeTeachingRouteChildren = {
  InnovativeTeachingMethodIdRoute: InnovativeTeachingMethodIdRoute,
}

const InnovativeTeachingRouteWithChildren =
  InnovativeTeachingRoute._addFileChildren(InnovativeTeachingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiAppsRoute: AiAppsRoute,
  ContactRoute: ContactRoute,
  DisasterManagementRoute: DisasterManagementRoute,
  ElectivesRoute: ElectivesRoute,
  EmDiariesRoute: EmDiariesRoute,
  FirstAidRoute: FirstAidRoute,
  Icem2026Route: Icem2026Route,
  InnovativeTeachingRoute: InnovativeTeachingRouteWithChildren,
  LinksRoute: LinksRoute,
  PatientEducationRoute: PatientEducationRoute,
  ResearchRoute: ResearchRoute,
  ResourcesRoute: ResourcesRoute,
  SocialServicesRoute: SocialServicesRoute,
  TeachingRoute: TeachingRoute,
  WorkshopsRoute: WorkshopsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
